version: '3'

services:
  monitor-ping:
    image: monitor-ping:latest
    container_name: monitor-ping
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ./:/app
      - ./logs:/app/logs

    logging:
      driver: json-file
      options:
        max-size: "10m"   # Define o tamanho máximo do arquivo de log para 10 megabytes
        max-file: "5"     # Mantém até 5 arquivos de log
