version: '3'

services:
  monitorping:
    image: monitorping:latest
    container_name: monitorping
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./logs:/app/logs

    logging:
      driver: json-file
      options:
        max-size: "10m"   # Define o tamanho máximo do arquivo de log para 10 megabytes
        max-file: "5"     # Mantém até 5 arquivos de log
